### ISSUE TITLE
Package is too heavyweight

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#349]
Hey guys - Cedar is too big because it’s including all of lodash and because it’s including lots of babel files to support ES6.

At a minimum, it would be good to change 
```import { isArray } from 'lodash'``` 
to 
```import isArray from 'lodash/isArray'```

https://github.com/rei/rei-cedar/blob/future-vue/src/components/radio/cdrRadio.vue#L20
https://github.com/rei/rei-cedar/blob/future-vue/src/components/select/cdrSelect.vue#L24

At an ideal state, we need cedar to [not bundle external dependencies](https://www.npmjs.com/package/webpack-node-externals). This may mean we need a separate build for UMD (if you want it available without externalized dependencies) and for commonjs2 (i.e. use on npm + node)

I took a stab at this, but I don’t know how to make this work with vue-loader because after adding `webpack-node-externals` it is including `core-js` as well as `vue-loader/lib/component-normalizer`. This means you'd need `vue-loader` and `babel-runtime` as dependencies in order for it to be properly distributable, but then again I don't know why it's including this in the first place so I thought I'd pass this bit off to you

**Comment by lancetharper** [comment]
Cedar won't be consumed the way you guys are currently getting it. You can get all of the components individually via npm instead of a few big files.

The latest stuff is much lighter and already has those lodash parts trimmed down. All of the components will come without dependencies (only peerDependencies).

[https://github.com/rei/rei-cedar/blob/npm-future-vue/src/components/radio/cdrRadio.vue#L25](https://github.com/rei/rei-cedar/blob/npm-future-vue/src/components/radio/cdrRadio.vue#L25)

The `future-vue` branch has basically been abandoned (and we'll probably remove it soon). [npm-future-vue](https://github.com/rei/rei-cedar/tree/npm-future-vue) is our current dev branch that we are getting ready to move over to master.
