### ISSUE TITLE
Source code is unnecessarily minified, making debugging difficult

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#353]
It is impossible to step through cedar components as they are completely minified.

It is not necessary to minify the source code, which is something that the final consumer of the package (i.e. the build for final bundling and web distribution) should be expected to do.

**Comment by KrisKnabel** [comment]
This is an interesting request.  I see the argument, but we should discuss as we may not want to provide this.  It opens the door for easier component customization by consumers which will break on updates and it reduces design control which is one of the main purposes of the design system.  @lancetharper should definitely chime in on this as I believe he knows more as to why we originally decided to supply the packaged in this way.

**Comment by jnields** [comment]
This doesn't have anything to do with customization - you can't customize the code just because the dist file is unminified.    Regardless, just the sentiments of the community seem to be that API should be documented and what is documented is the API regardless of what is "possible"

Whatever the case ... you could probably include source code in your bundle as well as some sourcemaps

This would let us debug cedar components if necessary

**Comment by KrisKnabel** [comment]
I believe it does relate and here is why.  Customization is less likely if the internal structure of something is not exposed.  If drilling into and stepping through internal component code, one may see that a one line change would solve a pressing issue.  This could entice one to fork the component and make the change.  If its a black box, the unknown is more of a deterrent.

I am not advocating one way or the other.  Just bringing up concepts that we should talk about when coming up with a decision.  Providing source maps and unminified source code may be in our best interest.  Alternatively, we may not want NON-Cedar folks debugging our components and would rather have defects/requests filed which may or may not have better outcomes.  For example, this request makes me think that we need to improve our documentation so that you shouldn't need to debug the component to know how it works.

We will discuss this early next week and come up with a decision.

**Comment by lancetharper** [comment]
It's a one-liner to undo minification, but I don't know that it's that useful since the source .vue file is still run through webpack and output as a umd library. So it isn't really useful "source code" whether what's currently there is minified or not. It isn't about code obfuscation to discourage forking/customizing, it wouldn't be open sourced if we were concerned about that 😄 

We can look at including the .vue file into the "files" array so it's available for reference from node_modules...but that still doesn't really help with debugging without sourcemaps which we'll have to add.

As far as API being documented, that's available both in the readme and on the doc site for all currently released (1.0+) components --> https://rei.github.io/rei-cedar-docs/components/buttons/?active-tab=api

**Comment by lancetharper** [comment]
We've republished all currently released components unminified + added source maps 👍
