### ISSUE TITLE
Add support for srcset and sizes

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#520]
I should be able to do something like this:
https://codepen.io/anon/pen/mQVWEZ

**Comment by mhewson** [comment]
@jnields, can you validate that this works for you or not? https://codesandbox.io/s/wwnr4jzwr7?module=%2Fsrc%2Fcomponents%2FExtending.vue

**Comment by jnields** [comment]
oh sorry, how about for `media-object`?

**Comment by mhewson** [comment]
I'll take a look at that - I think we would need to facilitate a way to pass these attributes into the image for that to work. We are still evaluating the necessity of the media-object and may roll out an update of the activity card that would remove it. Lets chat about what you would like to see here

**Comment by cowills** [comment]
@jnields since the media-object composition is no longer in cedar, and because cdr-img supports srcset and sizes, there does not appear to be anything left that we can do on this ticket. 

If you still require support for the media-object composition, let us know and we can work with you to port that into a FEDPACK component. (i partially started that work while trying to update adventures-ui/activity-card to the new cedar: https://git.rei.com/projects/FEDCOMP/repos/activity-card/pull-requests/18/overview)
