### ISSUE TITLE
How to use paginator without v-model?

### ISSUE THREAD

**Issue by jnields** [rei/rei-cedar-vue-2#605]
Directives, e.g. `v-model`, are not supported in jsx.

How do I use the paginator with jsx syntax?

**Comment by cowills** [comment]
would this work? https://github.com/vuejs/jsx#directives

Looks like you can implement the directive manually in JSX, though it's very awkward: https://vuejs.org/v2/guide/render-function.html#v-model

**Comment by zcrumbo** [comment]
I've had luck binding to `value` and subscribing to `change` events, which is basically what `v-model` is doing. There's some weird stuff that goes in with some inputs where the browser can hijack state that you need to account for.

**Comment by cowills** [comment]
it looks like we do some weird mapping related to `v-model`, for example in paginator it's `currentPage` not `value`. (https://github.com/rei/rei-cedar/blob/next/src/components/pagination/CdrPagination.vue#L134-L137)
ideally we would come up with a consistent naming pattern so that JSX users don't need to look at our source code to know how to pass the value prop in

**Comment by cowills** [comment]
https://rei.github.io/rei-cedar-docs/release-notes/fall-2019/?active-link=cdrpagination-cdrselect-and-cdrradio-v-model-binding#cdrpagination-cdrselect-and-cdrradio-v-model-binding 
as of cedar 3.0.0, pagination now binds it's v-model using the standard `value` and `@input` props: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
